### ISSUE TITLE
Outdated version on PyPI

### ISSUE THREAD

**Issue by IhateTrains** [cobusc/protected-media-prototype#13]
Hi, first of all I'd like to thank you for creating this package.

I noticed a [fix for Django 4](https://github.com/cobusc/django-protected-media/pull/12) got merged in and version in setup.py was bumped to 1.0.1: https://github.com/cobusc/django-protected-media/blob/acb05009d65763ce5b6246729f1cc2368f44ae7e/setup.py#L12

However, latest version on PyPI is still 1.0.0:
https://pypi.org/project/django-protected-media/#history
Is this intended?

**Comment by cobusc** [comment]
Hi Seweryn

Apologies. I forgot to publish the package. I uploaded it just now.

Regards,
  C

**Comment by DmytroLitvinov** [comment]
Hi @cobusc ,
If you need help with a future maintenance package at PyPI, you can also give me access to it. Here is my PyPI profile: https://pypi.org/user/DmytroLitvinov/

**Comment by DmytroLitvinov** [comment]
Published at PyPI version 1.0.1 - https://pypi.org/project/django-protected-media/1.0.1/

**Comment by IhateTrains** [comment]
Great, thank you!
