### ISSUE TITLE
'Settings' object has no attribute 'BASE_DIR'

### ISSUE THREAD

**Issue by danilogbotelho** [cobusc/protected-media-prototype#14]
BASE_DIR is not a mandatory entry in Django's settings.py. Thus, even though one defined PROTECTED_MEDIA_ROOT, an AttributeError exception will be thrown because of protected_media's own settings.py trying to define a default PROTECTED_MEDIA_ROOT using  BASE_DIR.

Protected-media's documentation doesn't make it clear BASE_DIR  is required as it probably shouldn't be.

**Comment by cobusc** [comment]
@danilogbotelho Thank you for reporting this. I'm going to make the error explicit, i.e. if PROTECTED_MEDIA_ROOT is not specified and BASE_DIR is not defined, then an explicit error will be raised for this:
```python
if not hasattr(settings, "PROTECTED_MEDIA_ROOT") and not hasattr(settings, "BASE_DIR"):
    raise RuntimeError("The default value for PROTECTED_MEDIA_ROOT requires BASE_DIR to be an available setting.")
```
This keeps backwards compatibility.

**Comment by cobusc** [comment]
Adressed in https://github.com/cobusc/django-protected-media/pull/16
