### ISSUE TITLE
Migrate to new CI platform

### ISSUE THREAD

**Issue by johnthagen** [cobusc/protected-media-prototype#15]
If you navigate to: https://travis-ci.org/github/cobusc/django-protected-media

> Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

travis-ci.com page 404's: https://www.travis-ci.com/cobusc/django-protected-media

It would seem the CI for this project is not running.

[As of Nov 2, 2020 Travis CI will no longer be free for FOSS projects](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

I would recommend moving to GitHub actions for CI.

**Comment by cobusc** [comment]
@johnthagen Addressed in https://github.com/cobusc/django-protected-media/pull/16 
Thanks for reporting.
