### ISSUE TITLE
Delete the file from the filesystem when the model with field gets deleted

### ISSUE THREAD

**Issue by Chris2L** [cobusc/protected-media-prototype#19]
Created a post_delete signal to catch the deletion of the model.  In the signal, I find the field and try to remove it with either
os.remove(os.path.join(f.path))
or 
default_storage.delete(f.path)

Both do the same under the hood, and both get this error:
The joined path (/path/to/project/protected/file.pdf) is located outside of the base path component (/path/to/project/media)

This error is raised by Django in utils/_os.py and raises SuspiciousFileOperation error.  Has anyone ever tried to delete their protected files?  Any advice?

**Comment by cobusc** [comment]
Hi @Chris2L 

Does `mymodel.protected_field.delete()` not work?

https://docs.djangoproject.com/en/4.2/ref/models/fields/#django.db.models.fields.files.FieldFile.delete

**Comment by Chris2L** [comment]
Hi @cobusc 

Yes, it does...  That is what happens if you code at 01:00.  I did follow the code but I never occurred to me that the main thing ProtectedFiles does is override the storage class to not use default_storage...
As a side note, the package Django-Cleanup also works with ProtectedFiles, as one should expect.

Thanks

**Comment by cobusc** [comment]
Glad you got it sorted out @Chris2L .

> That is what happens if you code at 01:00

:rofl: We've all been there.
