### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by morenoh149** [cobusc/protected-media-prototype#2]
I wanted to get this into awesome Django but they feel this project is not kept up to date. Could you update it?

Or say here that you welcome others updating the project? This way maybe someone submits a PR.

**Comment by cobusc** [comment]
Hi @morenoh149 I will welcome PRs for Python 3 and newer Django version support. It should be trivial to add these to the `.travis.yml` to see if the tests still pass. I'll see if I can do that tonight.

**Comment by cobusc** [comment]
@morenoh149 do you mind giving this a spin? https://github.com/cobusc/django-protected-media/pull/3

**Comment by cobusc** [comment]
@morenoh149 Feel free to get this into awesome Django list again. :)
