### ISSUE TITLE
ProtectedFileSystemStorage should extend the class defined by DEFAULT_FILE_STORAGE in settings.py instead of forcing FileSystemStorage

### ISSUE THREAD

**Issue by merabtenei** [cobusc/protected-media-prototype#20]
There is some cases where the default FileStorage is not the FileSystemStorage. For example we use Django with multitenancy where we defined ```DEFAULT_FILE_STORAGE = "django_pgschemas.contrib.files.TenantFileSystemStorage"``` in settings, we would like ProtectedFileSystemStorage to extend from this class to ensure the defined behavior remains unchanged.

**Comment by cobusc** [comment]
Hi @merabtenei 

Unfortunately I cannot extend an arbitrary base class, as it may well have unintended consequences. In this particular case, both `django-protected-media` and `django-pgschemas` modifies the behaviour of the `location` and `base_url` methods of the underlying `FileSystemStorage` class. If my `ProtectedFileSystem` class extended the `TenantFileSystemStorage` class, it would effectively overwrite those methods (and break it).

Both the aforementioned Django apps make changes to the `FileSystemStorage` base class to achieve its own goals, which in this case is conflicting.
