### ISSUE TITLE
Missing '/' in PROTECTED_MEDIA_URL by default

### ISSUE THREAD

**Issue by aliceni81** [cobusc/protected-media-prototype#8]
Hi,

I found that '/' is missing for default PROTECTED_MEDIA_URL "/protected/". Otherwise, the URL displayed is not the correct one.

# The URL prefix used by protected media
PROTECTED_MEDIA_URL = getattr(
    settings, "PROTECTED_MEDIA_URL", "**protected/**"
)

Alternatively, user has to define the settings by themselves.
PROTECTED_MEDIA_URL = '/protected/'

**Comment by cobusc** [comment]
Addressed in https://github.com/cobusc/django-protected-media/pull/16
